language: go
go:
  - 1.8.x
  - 1.9.x
sudo: required
services:
  - docker
before_install:
- docker pull rabbitmq
- docker run -d --rm --hostname test-rabbit --name gormqtool-test-rabbit -p 16672:15672 -p 6672:5672 rabbitmq:3-management
- docker ps -a
script:
- make test
